apiVersion: apps/v1
kind: Deployment
metadata:
  name: actio-identity
spec:
  selector:
    matchLabels:
      app: actio-identity-pod
  template:
    metadata:
      labels:
        app: actio-identity-pod
    spec:
      containers:
      - name: actio-identity-container
        image: mavidocker/actio.identity.service:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5051
---
apiVersion: v1
kind: Service
metadata:
  name: actio-identity-service
spec:
  selector:
    app: actio-identity-pod
  ports:
  - port: 8082
    targetPort: 5051
    nodePort: 30010
  type: NodePort

