apiVersion: apps/v1
kind: Deployment
metadata:
  name: actio-activities
spec:
  selector:
    matchLabels:
      app: actio-activities-pod
  template:
    metadata:
      labels:
        app: actio-activities-pod
    spec:
      containers:
      - name: actio-activities-container
        image: mavidocker/actio.activities.services:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: actio-activities-service
spec:
  selector:
    app: actio-activities-pod
  ports:
  - port: 8081
    targetPort: 5050
    nodePort: 30009
  type: NodePort

